### ISSUE TITLE
TypeError: i is undefined (vendor.js/leaflet)

### ISSUE THREAD

**Issue by mlutfy** [libremap/libremap-webui#1]
When loading the map, the web console shows: "TypeError: i is undefined" (vendor.js:191).

So I tried replacing:
- libremap-webui/vendor/leaflet/leaflet.js, with
- libremap-webui/vendor/leaflet/leaflet-src.js

And I got: "TypeError: obj is undefined" (vendor.js:247)

Being non-minimsed, the code was:

```
stamp: (function () {
    var lastId = 0,
        key = '_leaflet_id';
    return function (obj) {
        obj[key] = obj[key] || ++lastId; // line 247
        return obj[key];
    };
}()),
```

I wonder if it's related to this: https://github.com/Leaflet/Leaflet/issues/1282

**Comment by mlutfy** [comment]
I didn't dig in detail, but tested with the latest leaflet 0.7.1, and it didn't fix the issue.

I tested the master branch from 0.8.x, and got the error:

TypeError: layer is undefined (vendor.js 2498)

```
L.Map.include({
[...]
removeLayer: function (layer) {
    layer.remove(); // 2498
    return this;
},
```

not sure if that helps. I probably need to get a good book on NodeJS ;)

**Comment by andrenarchy** [comment]
thx for reporting! please update the dependencies, this should be fixed in the current version of couchmap-leaflet

**Comment by mlutfy** [comment]
Confirmed, that fixed the bug. Thanks!
